apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-gitlab
  template:
    metadata:
      labels:
        app: app-gitlab
    spec:
      containers:
        - name: gitlab-container
          image: gitlab/gitlab-ce:16.2.8-ce.0
          env:
            - name: DB_HOST
              value: postgres.local
            - name: DB_PORT
              value: "30007"
            - name: DB_NAME
              value: gitlab-db
            - name: DB_USER
              value: gitlab
            - name: DB_PASSWORD
              value: gitlab
            - name: GITLAB_ROOT_PASSWORD
              value: password
            - name: GITLAB_ROOT_EMAIL
              value: email@sample.com
          volumeMounts:
            - mountPath: /etc/gitlab
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-gitlab
