apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-gitlab
  template:
    metadata:
      labels:
        app: app-gitlab
    spec:
      containers:
        - name: gitlab-container
          image: gitlab/gitlab-ce:nightly
          env:
            - name: GITLAB_ROOT_EMAIL
              value: mavou-devops@sample.com
            - name: GITLAB_ROOT_PASSWORD
              value: M@vou@sample-password
          volumeMounts:
            - mountPath: /etc/gitlab
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-gitlab
