apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gitlab
  labels:
    type: local
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gitlab-storage-class
  local:
    path: /home/shermine237/gitlab-k8s/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - desktop-0n2dksr
