apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gitlab
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gitlab-storage-class
  local:
    path: /run/desktop/mnt/host/c/Users/path
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - docker-desktop
