apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitlab-conf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gitlab-storage-class
  volumeName: pv-gitlab-conf
  selector:
    matchLabels:
      type: local
